version: "3.4"
services:
 vite-app:
   image: node:18-alpine
   container_name: vite_docker
   entrypoint: /bin/sh
   ports:
     - 3000:3000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
  #  command: npm run dev